### ISSUE TITLE
How can I get the UDID?

### ISSUE THREAD

**Issue by popking5466** [Magic-Unique/MUMobileGestalt#1]
So can you tell me how can I get UDID ? 
NO step demos?

I Click "Quick request (default or custom)",then choose allow
It stay on the settings screen and nothing happening .

**Comment by Magic-Unique** [comment]
I'm sorry for the demo. It has not completed.

If you want to run demo and get UDID, you can follow these steps:

1. Run in simulator or iOS device
2. Click "Quick Request (Custom)" (It will open Safari)
3. Click "Allow" in Safari (It will open Preferences)
4. Click "Install" in Preferences
5. It will open Demo, and your UDID will log in console.

**Comment by popking5466** [comment]
Yes i did it now.
Thx a lot.
:)

**Comment by popking5466** [comment]
Another issue:
When get UDID successfully once.Every tableview cell "didselect" delegate not response.

**Comment by Magic-Unique** [comment]
Sure ?

When I click "Quick Request (Custom)" after I got successfully. it work again.

**Comment by popking5466** [comment]
Emmm.Maybe it's the issue of iOS 12.1 .
I delete the app and isntall again, It worked ..

**Comment by Magic-Unique** [comment]
Oh, so interesting.
