### ISSUE TITLE
偶尔有从safari跳转系统设置下载配置文件失败的情况

### ISSUE THREAD

**Issue by 983563622** [Magic-Unique/MUMobileGestalt#2]
这种情况很少见，但是一旦出现，浏览器和系统设置页面不杀掉，会一直出现这种情况，只有将浏览器和系统设置页面杀掉才能再次安装恢复正常，系统是 iOS12.1 iPhone6s Plus

**Comment by Magic-Unique** [comment]
你是说跳转到设置后，并没有弹出描述文件的界面？

**Comment by 983563622** [comment]
是的 偶尔

**Comment by Magic-Unique** [comment]
这是系统的 bug，没有办法解决。只能杀掉 Safari 和设置。

**Comment by 983563622** [comment]
你也有遇到过吗? 我也只是偶尔遇到过 不过iOS12.2之后的系统流程发生了变化 不再是Safari跳转设置直接安装 而是一个Alert提示去设置安装已下载的配置文件

**Comment by Magic-Unique** [comment]
嗯，连续安装多次就会出现这种情况。只能杀进程。

iOS 12.2 流程变化，目前只能按照系统的提示手动去设置里安装描述文件。

**Comment by 983563622** [comment]
嗯 好的 谢谢你的答复
